name: Deploy Terraform

on:
  workflow_dispatch:

env:
  TF_VAR_project_id: deft-epigram-375817
  GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

jobs:
  DeployDataflow:
    runs-on: ubuntu-latest

    steps:
    - name: Enable GitHub Actions
      uses: actions/checkout@v3.3.0

    - id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.TF_VAR_project_id }}

    - name: Configure Terraform
      uses: hashicorp/setup-terraform@v2.0.3


    - name: Deploy Terraform
      run: |
        cd Dataflow
        terraform init
        terraform plan 
        terraform apply 
